### ISSUE TITLE
Errors after launching go-architect in Ubuntu 20.04

### ISSUE THREAD

**Issue by userg3003** [fdaines/go-architect#19]
Hi.
I tried to compile the project in Ubuntu with **make install**:
# Wails
Version         | v2.7.1
Package Manager | apt   

# System
┌──────────────────────────────────────────────────────────────┐
 | OS           | Ubuntu                                        |
 | Version      | 20.04                                         |
 | ID           | ubuntu                                        |
 | Go Version   | go1.19.13                                     |
 | Platform     | linux                                         |
 | Architecture | amd64                                         |
 | CPU          | 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz |
 | GPU          | unknown (Intel Corporation) - Driver: i915    |
 | Memory       | 32GB                                          |
└──────────────────────────────────────────────────────────────┘

# Dependencies
┌──────────────────────────────────────────────────────────────────────────┐
 | Dependency | Package Name          | Status    | Version                 |
 | *docker    | docker.io             | Installed | 24.0.2                  |
 | gcc        | build-essential       | Installed | 12.8ubuntu1.1           |
 | libgtk-3   | libgtk-3-dev          | Installed | 3.24.20-0ubuntu1.1      |
 | libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.38.6-0ubuntu0.20.04.1 |
 | npm        | npm                   | Installed | 8.19.4                  |
 | *nsis      | nsis                  | Available | 3.05-2                  |
 | pkg-config | pkg-config            | Installed | 0.29.1                  | 
└──────────────────────── * - Optional Dependency ─────────────────────────┘

# Diagnosis
Optional package(s) installation details: 
  - nsis: sudo apt install nsis

 SUCCESS  Your system is ready for Wails development!

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
CGO_ENABLED=1 wails build -clean
Wails CLI v2.7.1

# Build Options

Platform(s)        | linux/amd64                                     
Compiler           | /home/userg/go1.19/go1.19.13/bin/go             
Skip Bindings    | false                                           
Build Mode        | production                                      
Devtools            | false                                           
Frontend Directory | ./go-architect/frontend
Obfuscated         | false                                           
Skip Frontend      | false                                           
Compress           | false                                           
Package            | true                                            
Clean Bin Dir      | true                                            
LDFlags            |                                                 
Tags               | []                                              
Race Detector      | false                                           
Warning: go.mod is using Wails '2.6.0' but the CLI is 'v2.7.1'. Consider updating your project's `go.mod` file.

# Building target: linux/amd64

  • Generating bindings: 2023/12/25 18:34:38 KnownStructs: comments.CommentsMetrics     coupling.DependencyCoupling     dependency.ModuleDependencyGraph        dsm.DependencyStructureMatrix   git.VCSAnalysisInfo   gocyclo.GoCycloOutput   instability.PackageInstability  interfaces.InterfaceInfo        interfaces.InterfaceMetrics     loc.FileLOC     loc.PackageLOC  loc.ProjectLOC  project.ProjectInfo     repository.RepositoryInfo     storage.HistoricalMetrics       storage.Metrics storage.Project storage.ProjectList     storage.SelectedProject types.PackageTypes      types.ProjectTypes
storage.Metrics

Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend: Done.
  • Compiling application: Done.
  • Packaging application: Done.
Built '/home/userg/projects/tools/go-architect/build/bin/go-architect' in 35.098s.

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
make[1]: выход из каталога «/home/userg/projects/tools/go-architect»
Your Go-Architect executable was generated in current folder

After launch ./go-architect received the following errors:
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
signal 11 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag

runtime stack:
runtime.throw({0xb783bc?, 0xc000074000?})
        /home/userg/go1.19/go1.19.13/src/runtime/panic.go:1047 +0x5d fp=0xc0000eebe0 sp=0xc0000eebb0 pc=0x43d95d
runtime.sigNotOnStack(0xb)
        /home/userg/go1.19/go1.19.13/src/runtime/signal_unix.go:1024 +0x65 fp=0xc0000eec00 sp=0xc0000eebe0 pc=0x4541c5
runtime.adjustSignalStack(0xb, 0x13527a0, 0xc0000eec90)
        /home/userg/go1.19/go1.19.13/src/runtime/signal_unix.go:581 +0x28b fp=0xc0000eec68 sp=0xc0000eec00 pc=0x452d4b
runtime.sigtrampgo(0xb, 0xc0000eef70, 0xc0000eee40)
        /home/userg/go1.19/go1.19.13/src/runtime/signal_unix.go:469 +0x15b fp=0xc0000eece0 sp=0xc0000eec68 pc=0x4528bb
runtime.sigtramp()
        /home/userg/go1.19/go1.19.13/src/runtime/sys_linux_amd64.s:359 +0x46 fp=0xc0000eed30 sp=0xc0000eece0 pc=0x470286

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/userg/go1.19/go1.19.13/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000084fe8 sp=0xc000084fe0 pc=0x46e661

goroutine 1 [running, locked to thread]:
        goroutine running on other thread; stack unavailable

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/userg/go1.19/go1.19.13/src/runtime/proc.go:363 +0xd6 fp=0xc000070fb0 sp=0xc000070f90 pc=0x4405b6
runtime.goparkunlock(...)
        /home/userg/go1.19/go1.19.13/src/runtime/proc.go:369
runtime.forcegchelper()
        /home/userg/go1.19/go1.19.13/src/runtime/proc.go:302 +0xad fp=0xc000070fe0 sp=0xc000070fb0 pc=0x44044d
runtime.goexit()
        /home/userg/go1.19/go1.19.13/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000070fe8 sp=0xc000070fe0 pc=0x46e661
created by runtime.init.6
        /home/userg/go1.19/go1.19.13/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/userg/go1.19/go1.19.13/src/runtime/proc.go:363 +0xd6 fp=0xc000071790 sp=0xc000071770 pc=0x4405b6
runtime.goparkunlock(...)
        /home/userg/go1.19/go1.19.13/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
        /home/userg/go1.19/go1.19.13/src/runtime/mgcsweep.go:278 +0x8e fp=0xc0000717c8 sp=0xc000071790 pc=0x42cdce
runtime.gcenable.func1()
        /home/userg/go1.19/go1.19.13/src/runtime/mgc.go:178 +0x26 fp=0xc0000717e0 sp=0xc0000717c8 pc=0x421a86
runtime.goexit()
        /home/userg/go1.19/go1.19.13/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000717e8 sp=0xc0000717e0 pc=0x46e661
created by runtime.gcenable
        /home/userg/go1.19/go1.19.13/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000044070?, 0xf12930?, 0x1?, 0x0?, 0x0?)
        /home/userg/go1.19/go1.19.13/src/runtime/proc.go:363 +0xd6 fp=0xc000071f70 sp=0xc000071f50 pc=0x4405b6
runtime.goparkunlock(...)
        /home/userg/go1.19/go1.19.13/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x13519a0)
        /home/userg/go1.19/go1.19.13/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc000071fa0 sp=0xc000071f70 pc=0x42ae73
runtime.bgscavenge(0x0?)
        /home/userg/go1.19/go1.19.13/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc000071fc8 sp=0xc000071fa0 pc=0x42b445
runtime.gcenable.func2()
        /home/userg/go1.19/go1.19.13/src/runtime/mgc.go:179 +0x26 fp=0xc000071fe0 sp=0xc000071fc8 pc=0x421a26
runtime.goexit()
        /home/userg/go1.19/go1.19.13/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000071fe8 sp=0xc000071fe0 pc=0x46e661
created by runtime.gcenable
        /home/userg/go1.19/go1.19.13/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x13527a0?, 0xc000007860?, 0x0?, 0x0?, 0xc000070770?)
        /home/userg/go1.19/go1.19.13/src/runtime/proc.go:363 +0xd6 fp=0xc000070628 sp=0xc000070608 pc=0x4405b6
runtime.goparkunlock(...)
        /home/userg/go1.19/go1.19.13/src/runtime/proc.go:369
runtime.runfinq()
        /home/userg/go1.19/go1.19.13/src/runtime/mfinal.go:180 +0x10f fp=0xc0000707e0 sp=0xc000070628 pc=0x420b8f
runtime.goexit()
        /home/userg/go1.19/go1.19.13/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000707e8 sp=0xc0000707e0 pc=0x46e661
created by runtime.createfing
        /home/userg/go1.19/go1.19.13/src/runtime/mfinal.go:157 +0x45

goroutine 6 [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/userg/go1.19/go1.19.13/src/runtime/proc.go:363 +0xd6 fp=0xc0000726d0 sp=0xc0000726b0 pc=0x4405b6
runtime.chanrecv(0xc0001fc900, 0xc0000727a8, 0x1)
        /home/userg/go1.19/go1.19.13/src/runtime/chan.go:583 +0x49b fp=0xc000072760 sp=0xc0000726d0 pc=0x40eafb
runtime.chanrecv2(0x0?, 0x0?)
        /home/userg/go1.19/go1.19.13/src/runtime/chan.go:447 +0x18 fp=0xc000072788 sp=0xc000072760 pc=0x40e638
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).startRequestProcessor(0xc0001fdbc0)
        /home/userg/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/linux/frontend.go:494 +0x5d fp=0xc0000727c8 sp=0xc000072788 pc=0xa026dd
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend.func3()
        /home/userg/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/linux/frontend.go:179 +0x26 fp=0xc0000727e0 sp=0xc0000727c8 pc=0xa01186
runtime.goexit()
        /home/userg/go1.19/go1.19.13/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000727e8 sp=0xc0000727e0 pc=0x46e661
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend
        /home/userg/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/linux/frontend.go:179 +0x53c

goroutine 7 [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/userg/go1.19/go1.19.13/src/runtime/proc.go:363 +0xd6 fp=0xc000072ec8 sp=0xc000072ea8 pc=0x4405b6
runtime.chanrecv(0xc0001fc8a0, 0xc000072fa8, 0x1)
        /home/userg/go1.19/go1.19.13/src/runtime/chan.go:583 +0x49b fp=0xc000072f58 sp=0xc000072ec8 pc=0x40eafb
runtime.chanrecv2(0x0?, 0x0?)
        /home/userg/go1.19/go1.19.13/src/runtime/chan.go:447 +0x18 fp=0xc000072f80 sp=0xc000072f58 pc=0x40e638
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).startMessageProcessor(0x0?)
        /home/userg/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/linux/frontend.go:208 +0x59 fp=0xc000072fc8 sp=0xc000072f80 pc=0xa01219
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend.func4()
        /home/userg/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/linux/frontend.go:182 +0x26 fp=0xc000072fe0 sp=0xc000072fc8 pc=0xa01126
runtime.goexit()
        /home/userg/go1.19/go1.19.13/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000072fe8 sp=0xc000072fe0 pc=0x46e661
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend
        /home/userg/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/linux/frontend.go:182 +0x57f

**Comment by Gorbovskyfallz** [comment]
same issue, but for manjaro. Checked 0.4.0 release - same result, Downgraded wails to 2.6.0 - without changes

**Comment by fdaines** [comment]
Thanks for sharing, I'm creating a similar environment (Ubuntu 20.04, Go 1.19.13, Npm 8.19.4) to reproduce the problem. 
As soon as I can reproduce the issue I will try to find out the reason.

**Comment by lechuhuuha** [comment]
> Thanks for sharing, I'm creating a similar environment (Ubuntu 20.04, Go 1.19.13, Npm 8.19.4) to reproduce the problem. As soon as I can reproduce the issue I will try to find out the reason.

thanks having same problem

**Comment by fdaines** [comment]
Guys, could you check if the [ubuntu-2004-error](https://github.com/go-architect/go-architect/tree/ubuntu-2004-error) branch fixed the problem?

```sh
git clone -b ubuntu-2004-error https://github.com/go-architect/go-architect.git
cd go-architect
make install
./go-architect
```

or 
```sh
cd go-architect
git pull
git checkout ubuntu-2004-error
make install
./go-architect
```

**Comment by Gorbovskyfallz** [comment]
So, not on ubuntu, but on manjaro i tested c93eca7c, and at first sight - everythink is ok - i could add my project and get metricts for it, thanks a lot!  (go 1.21.5, 6.1.69-manjaro,  wails 2.7.1)

**Comment by fdaines** [comment]
Thanks @Gorbovskyfallz , can you share in this issue your environment (Manjaro version, Go version and NPM version)?

**Comment by Gorbovskyfallz** [comment]
@fdaines
npm: 10.2.5
wails: 2.7.1
manjaro:  6.1.69-1-MANJARO #1 SMP PREEMPT_DYNAMIC  2023 x86_64 GNU/Linux
go version : 1.21.5

**Comment by lechuhuuha** [comment]
> Guys, could you check if the [ubuntu-2004-error](https://github.com/go-architect/go-architect/tree/ubuntu-2004-error) branch fixed the problem?
> 
> ```shell
> git clone -b ubuntu-2004-error https://github.com/go-architect/go-architect.git
> cd go-architect
> make install
> ./go-architect
> ```
> 
> or
> 
> ```shell
> cd go-architect
> git pull
> git checkout ubuntu-2004-error
> make install
> ./go-architect
> ```

thanks i can run ./go-architect without any problems and can the other metrics and depencies graph
