### ISSUE TITLE
Error during make install

### ISSUE THREAD

**Issue by MarcelH-Tabeo** [fdaines/go-architect#23]
Done.
  • Installing frontend dependencies:     
    
  ERROR   exec: "npm": executable file not found in $PATH
  
  An instruction about this is clearly missing  at "Requirements"

**Comment by MarcelH-Tabeo** [comment]
Solution:
Install NodeJS via:
https://nodejs.org/en/download/
(npm will be installed too)

**Comment by fdaines** [comment]
This requirement and its solution will be added in the documentation.
